### PR TITLE
Implement soa parsing

### PR DESCRIPTION
**Pull request by rigdent**
Implement SOA record type parsing.

I am unsure how to deal with the SOA enum type. Should I leave it as is below, or should I create a struct for it since it has so many fields? I personally don't even need all the fields; I just figured that I might as well parse them all.

Thoughts? I will create tests after deciding on this.

Thanks!

### CODE REVIEW

**Comment by tailhook** [comment]
I think creating a structure would be more convenient for working with SOA records.

**Comment by rigdent** [comment]
@tailhook I've updated this branch to use a `SoaRecord` struct. If you have any changes you would like done regarding names or whatnot, let me know.

Also, I found a bug in the `OpCode` parsing.
Here: https://github.com/tailhook/dns-parser/blob/master/src/header.rs#L45
The bitwise shift was happening to the `flag::OPCODE_MASK` instead of the result of the bitwise and. 
So the bitwise and only checked the last 4 bits of `flags` which is the response code, and since all the tests besides my soa test had `NoError` for the response code, all the other tests passed.

**Comment by tailhook** [comment]
Nice catch. Thanks!

**Comment by tailhook** [comment]
Released v0.3.4. 

By the way, feel free to add yourself to the list of the authors of the library.

**Pull request merged**
