### PR TITLE
Auto generate enums and RData implementation

### PR DESCRIPTION
**Pull request by rushmorem**
This commit continues from where 8ebd02cd12e99932feb91c700a92c230a225cc94 left off. It automatically generates the following code:-

* `Type` and `QueryType` enums and their implementations
* `RData` implementation

### CODE REVIEW

**Comment by tailhook** [comment]
Well, I try to avoid auto-generation as much as possible. I don't think it's required in this case. New types are not added often. I think nowadays new record types appear not more frequently than once a year, so it's not a big problem to just add a one or two lines of code in 5 places.

**Comment by rushmorem** [comment]
> Well, I try to avoid auto-generation as much as possible.

I can see how auto-generation can cause problems. I tried to make this implementation as straight forward as possible to avoid any "magic". However, without knowing your specific reasons for avoiding it, I can only speculate. Mind explaining a bit further?

> I don't think it's required in this case. New types are not added often.

While it is true that new types are not added often we already have so many types that adding them manually, and not to mention maintaining them, is a daunting task.

> ... it's not a big problem to just add a one or two lines of code in 5 places.

Well after this pull request, we only have to add them in 2 places:-

- in `/src/rdata/TYPE_NAME.rs` to implement the `Record` trait
- in `/src/rdata/config.rs`, if necessary, to configure how the type is stored in `RData`

This implementation only generates boring stuff like the straight forward enums and the match for `RData` implementation as well as configuring imports. I think this is a huge win for productivity. This is why I think auto generating this stuff is perfect in this case.

If I can persuade you to land this, I have another pull request waiting that adds stubs for all the other types remaining (to the best of my knowledge) which effectively eliminates boilerplate for adding new types.

**Comment by tailhook** [comment]
> However, without knowing your specific reasons for avoiding it, I can only speculate. Mind explaining a bit further?

Well, it's based on my experience. Usually, it causes more problems than it solves.

Picking single important reason: it's totally impossible to review the code on github. You need to generate the actual code to find out whether it's okay.

Your commit is `+159 −240` So it basically has the same amount of code, But previously it was for plain simple straightforward code, now it contains basically unreadable code formatting code. Where the only way to find out what happens is generating the code and see what has been generated.

So generating code makes sense for `serde` where you have lots of users of code tested once. But not for this case.

>  I think this is a huge win for productivity.

It's not. Implementing single Record parser is much more effort. You need to read the spec, understand semantics, implement in code. Watch out for edge cases.

Adding 4 enums, is just adding 4 lines of clean predictable, although boring code. Ergonomics and productivity is not about lines of code, it's about complexity of the code.

**Comment by rushmorem** [comment]
I see. You make a persuasive case. I respect your decision.

**Comment by tailhook** [comment]
Hopefully, this doesn't discourage you. I appreciate your contributions anyway!

**Pull request closed without merging**
