### PR TITLE
Add NSEC type

### PR DESCRIPTION
**Pull request by janderholm**
I've encountered mDNS responses with the NSEC type. Apparently RFC 6762 uses it to signal there are no further records:

https://osqa-ask.wireshark.org/questions/59944/whats-the-meaning-of-these-nsec-records-in-mdns-response-packet

I don't personally use the record, but the parsing of a packet containing it will return an Error unless there's an implementation of the record.

An alternative to this could be to create an Unknown or Unimplemented type and let Type::parse in enums.rs return this instead of an error when encountering things is does not recognize.

### CODE REVIEW

**Comment by tailhook** [comment]
>  it will return an Error unless there's an implementation of the record.

I'm still not sure how this commit helps. It will crash on `unimplemented` later, right?

> An alternative to this could be to create an Unknown or Unimplemented type and let Type::parse in enums.rs return this instead of an error when encountering things is does not recognize.

I think we need to add `__Nonexhaustive` option to add future types. But I'm not sure it will help here. What exact problem do you solve? If you can't parse packet it's perfectly okay that parser errors. Or do you want to inspect other parts of the packet header?

**Comment by janderholm** [comment]
> I'm still not sure how this commit helps. It will crash on unimplemented later, right?

It will only panic if `nsec::Record::parse` is called. But it is never called because `RData::parse` will return an `Ok(RData::Unknown(rdata))`. So it is mimicking what most other records, such as hinfo, are doing.

> What exact problem do you solve? If you can't parse packet it's perfectly okay that parser errors. Or do you want to inspect other parts of the packet header?

The problem I am trying to solve is parsing a packet with some additional records (NSEC in this case) which are not recognized by the library. These are packets coming from rendezvous so it affects pretty much all apple devices (Apple TV included), things like Kodi and a large amount of mDNS devices out there. Probably almost every mDNS service running on Mac OS as well.

I am using `dns_parser::Packet::parse` and since the record is not in `Type::parse`, it will fail the parsing completely. It is a valid DNS packet, it just happens that this library does not (yet) recognize that specific record type. There are quite a few DNS record types in existence that are not recognized by the library yet:
https://en.wikipedia.org/wiki/List_of_DNS_record_types

Now  I don't actually care about the NSEC record. In this context it means something like, there are no more names available, and I only care about the TXT records. I think receiving a parsed `Packet` in case a record cannot be parsed is a good thing. That means I can simply ignore it. The unknown type even gives access to the data so you can do whatever you want with it, such as present the raw bytes to the user. If my use case considers unparsable records an error I can simply decide that myself.

**Comment by janderholm** [comment]
I just thought of another possibility. It would be possible to add the function `Packet::parse_lossy`. That function would behave like `Packet::parse` except it inserts dummy unknown records whenever it encounters something it does not understand. Sort of like [`String::from_utf8_lossy`](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8_lossy).

**Comment by tailhook** [comment]
Ah, sorry, now I see. Okay, I've merged it in, at least it's matches what we do with other yet unparseable entries.

**Comment by janderholm** [comment]
Thanks!

**Pull request merged**
